In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

Creating Numpy Arrays

In [2]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)

array([[-0.26381106,  0.47863577],
       [-1.03276644, -0.19676513],
       [ 0.35409025,  0.00595965]])

Array Attributes

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


Array Operations

In [5]:
# Basic Math
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [6]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [7]:
# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

Indexing & Slicing

In [8]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]

array([1, 3, 5])

In [9]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

array([4, 5])

In [11]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

Reshaping & Combining Arrays

In [12]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [14]:
# Stacking
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

Broadcasting

In [15]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

Saving & Loading Arrays

In [17]:
# Save to a file
np.save('array.npy', arr)

In [19]:
# Load from a file
loaded_arr = np.load('array.npy')